Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'APPT-TYPE', content: 'C', value: 'C', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'APPT-TYPE', content: 'E', value: 'E', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_ TITLE', content: 'BR CH', value: 'BR CH', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Chief Counsel Policy and Proc', value: 'Chief Counsel Policy and Proc', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Deputy DIR', value: 'Deputy DIR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'General Attorney', value: 'General Attorney', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Admn Officer', value: 'Admn Officer', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Associate Counsel', value: 'Associate Counsel', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Assistant Chief', value: 'Assistant Chief', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Assistant Director', value: 'Assistant Director', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Acting Chairman', value: 'BD-Acting Chairman', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Acting Vice Chairman', value: 'BD-Acting Vice Chairman', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Ch Mbr', value: 'BD-Ch Mbr', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Chairman', value: 'BD-Chairman', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Chief Counsel', value: 'BD-Chief Counsel', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-DVC', value: 'BD-DVC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Law Mbr', value: 'BD-Law Mbr', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Sr DVC', value: 'BD-Sr DVC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Vice Chairman', value: 'BD-Vice Chairman', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Chief', value: 'Chief', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Clerk', value: 'Clerk', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Clerk (Summer)', value: 'Clerk (Summer)', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Computer Specialist', value: 'Computer Specialist', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Counsel', value: 'Counsel', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Deputy Chief Counsel', value: 'Deputy Chief Counsel', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Executive Assistant', value: 'Executive Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Lead OA Assistant', value: 'Lead OA Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Legal Assistant', value: 'Legal Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Legal Clerk', value: 'Legal Clerk', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Legal Clerk (Summer)', value: 'Legal Clerk (Summer)', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Mail & File Clerk', value: 'Mail & File Clerk', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Medical Adviser', value: 'Medical Adviser', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Mgmt Analyst', value: 'Mgmt Analyst', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'OA Assistant', value: 'OA Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'OA Asst/Computer Asst', value: 'OA Asst/Computer Asst', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'OA Clerk', value: 'OA Clerk', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Paralegal Specialist', value: 'Paralegal Specialist', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Personnel Assistant', value: 'Personnel Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Program Analyst', value: 'Program Analyst', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Program Sup Asst', value: 'Program Sup Asst', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Program Sup Clerk', value: 'Program Sup Clerk', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Program Sup Clerk (Summer)', value: 'Program Sup Clerk (Summer)', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Secretary', value: 'Secretary', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Special Assistant', value: 'Special Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Staff Assistant', value: 'Staff Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Staff Counsel', value: 'Staff Counsel', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Team Leader', value: 'Team Leader', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Program Specialist', value: 'Program Specialist', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Computer Assistant', value: 'Computer Assistant', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Law Clerk', value: 'Law Clerk', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Information Technology Spec', value: 'Information Technology Spec', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Administrative Specialist', value: 'Administrative Specialist', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'BD-Senior Counsel', value: 'BD-Senior Counsel', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Law Librarian', value: 'Law Librarian', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Chief Counsel for Operations', value: 'Chief Counsel for Operations', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Principal Deputy Vice Chairman', value: 'Principal Deputy Vice Chairman', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Supvr Admin Svc Mgr', value: 'Supvr Admin Svc Mgr', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Spec Projects Officer', value: 'Spec Projects Officer', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Division CH', value: 'Division CH', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Administrative Service Manager', value: 'Administrative Service Manager', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Contact Representative', value: 'Contact Representative', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'SR Qual Assurance Officer', value: 'SR Qual Assurance Officer', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'BVA_TITLE', content: 'Dir, Mgmt, Planning & Analysis', value: 'Dir, Mgmt, Planning & Analysis', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08b2-CORRS SEC', value: '08b2-CORRS SEC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08a-CASE SPT BR ', value: '08a-CASE SPT BR ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08a4-TRANSLATION  ', value: '08a4-TRANSLATION  ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08a1-CASE REV ', value: '08a1-CASE REV ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08b1-IT INVEN/SUPPLY', value: '08b1-IT INVEN/SUPPLY', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08b3-MAIL PROC/CASE ', value: '08b3-MAIL PROC/CASE ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '06-DEPUTY DIR ', value: '06-DEPUTY DIR ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '06a-HR ', value: '06a-HR ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '07-FIN MGT DIV', value: '07-FIN MGT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '07a-BUDGET EXECUTE', value: '07a-BUDGET EXECUTE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '07a1-TRAVEL', value: '07a1-TRAVEL', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '07a2-BUS. PERFORMANCE', value: '07a2-BUS. PERFORMANCE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '01-CH', value: '01-CH', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '02b-VC/BGT', value: '02b-VC/BGT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '02-VC', value: '02-VC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '02a-VC/MIS', value: '02a-VC/MIS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '12-HRG', value: '12-HRG', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '03b-APP GRP/HR', value: '03b-APP GRP/HR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '03a-APP GRP/SUPP', value: '03a-APP GRP/SUPP', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '03-APP GRP', value: '03-APP GRP', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '03c-APP GRP/MED', value: '03c-APP GRP/MED', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '11-D2', value: '11-D2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '11-D2a', value: '11-D2a', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '12-D3a', value: '12-D3a', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '10-D1', value: '10-D1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '10-D1a', value: '10-D1a', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '13-D4a', value: '13-D4a', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '10-D1', value: '10-D1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '10-DEV', value: '10-DEV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '13-D4', value: '13-D4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '11-INTAKE', value: '11-INTAKE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '12-D3', value: '12-D3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '10-D1', value: '10-D1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: 'Sr.Counsel to the Board', value: 'Sr.Counsel to the Board', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09-DEC TM SPT DIV', value: '09-DEC TM SPT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09a-Hearing Br', value: '09a-Hearing Br', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09a1-CO HEARINGS', value: '09a1-CO HEARINGS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09a3-CASE MGT', value: '09a3-CASE MGT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09a4-TRVL BOARD', value: '09a4-TRVL BOARD', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09b-DISPATCH BR', value: '09b-DISPATCH BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09b1-DISPATCH', value: '09b1-DISPATCH', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09b2-DT SPT STAFF', value: '09b2-DT SPT STAFF', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09c-CASE MGT BR', value: '09c-CASE MGT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09c1-CASE MGT', value: '09c1-CASE MGT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09c2-AOD', value: '09c2-AOD', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09c3-OMO', value: '09c3-OMO', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08-ADMIN SPT DIV', value: '08-ADMIN SPT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08a2-TRANSCRIPT', value: '08a2-TRANSCRIPT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08a3-WB SEC ', value: '08a3-WB SEC ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08b-CLERICAL SPT BR', value: '08b-CLERICAL SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09-DT SPT  DIV', value: '09-DT SPT  DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '09a2-VIDEO HEARING', value: '09a2-VIDEO HEARING', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '05-OMPA', value: '05-OMPA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'EOM', content: '08b4-FIELD REP/OMB', value: '08b4-FIELD REP/OMB', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'AL-02', value: 'AL-02', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-15', value: 'GS-15', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'ES-05', value: 'ES-05', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'ES-4', value: 'ES-4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'EX-IV', value: 'EX-IV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-01', value: 'GS-01', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-02', value: 'GS-02', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-03', value: 'GS-03', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-04', value: 'GS-04', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-05', value: 'GS-05', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-06', value: 'GS-06', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-07', value: 'GS-07', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-08', value: 'GS-08', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-09', value: 'GS-09', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-11', value: 'GS-11', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-12', value: 'GS-12', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-13', value: 'GS-13', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'GS-14', value: 'GS-14', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'GRADE', content: 'AL-03', value: 'AL-03', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0301', value: '0301', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0303', value: '0303', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0305', value: '0305', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0313', value: '0313', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0318', value: '0318', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0326', value: '0326', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0334', value: '0334', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0341', value: '0341', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0343', value: '0343', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0350', value: '0350', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0602', value: '0602', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0905', value: '0905', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0950', value: '0950', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0986', value: '0986', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0335', value: '0335', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '0904', value: '0904', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '2210', value: '2210', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'JOB_CODE', content: '1410', value: '1410', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'OWKR_GROUP', content: 'BUSINESS PERFORM', value: 'BUSINESS PERFORM', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'ADMINISTRATIVE OFFIC', value: 'ADMINISTRATIVE OFFIC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'SPVR ADMIN SVC MGR', value: 'SPVR ADMIN SVC MGR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'CLERK', value: 'CLERK', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'CLERK (SUMMER)', value: 'CLERK (SUMMER)', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'COM SPEC TEAM LEADER', value: 'COM SPEC TEAM LEADER', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'COMPUTER SPECIALIST', value: 'COMPUTER SPECIALIST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'DUPLICATING EQPT OPR', value: 'DUPLICATING EQPT OPR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'GENERAL ATTORNEY', value: 'GENERAL ATTORNEY', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'LEGAL ASSISTANT', value: 'LEGAL ASSISTANT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'LEGAL ASSISTANT/OA', value: 'LEGAL ASSISTANT/OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'LEGAL CLERK', value: 'LEGAL CLERK', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'LEGAL CLERK /OA', value: 'LEGAL CLERK /OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'MAIL & FILE CLERK', value: 'MAIL & FILE CLERK', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'MANAGEMENT ANALYST', value: 'MANAGEMENT ANALYST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'MEDICAL OFFICER', value: 'MEDICAL OFFICER', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'OFFICE AUTO ASST/OA', value: 'OFFICE AUTO ASST/OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'OFFICE AUTO CLERK/OA', value: 'OFFICE AUTO CLERK/OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PARALEGAL SPECIALIST', value: 'PARALEGAL SPECIALIST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PROGRAM ANALYST', value: 'PROGRAM ANALYST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PROGRAM SUP ASST', value: 'PROGRAM SUP ASST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PROGRAM SUP ASST/OA', value: 'PROGRAM SUP ASST/OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PROGRAM SUP CLERK', value: 'PROGRAM SUP CLERK', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PROGRAM SUP CLERK/OA', value: 'PROGRAM SUP CLERK/OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'SECRETARY', value: 'SECRETARY', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'SECRETARY/OA', value: 'SECRETARY/OA', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'STAFF ASSISTANT', value: 'STAFF ASSISTANT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'SUPR PARALEGAL SP', value: 'SUPR PARALEGAL SP', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'TRANSCRIP UNIT SUPR', value: 'TRANSCRIP UNIT SUPR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'CHAIRMAN', value: 'CHAIRMAN', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PRINCIPAL DEPUTY VC', value: 'PRINCIPAL DEPUTY VC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'BD-ACTING CHAIRMAN', value: 'BD-ACTING CHAIRMAN', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'ATTY-ADVISER/VET', value: 'ATTY-ADVISER/VET', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'LAW LIBRARIAN', value: 'LAW LIBRARIAN', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'ADMIN SPECIALIST', value: 'ADMIN SPECIALIST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'LAW CLERK', value: 'LAW CLERK', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'INFO TECHNOLOGY SPEC', value: 'INFO TECHNOLOGY SPEC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'VICE CHAIRMAN', value: 'VICE CHAIRMAN', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'COMPUTER ASSISTANT', value: 'COMPUTER ASSISTANT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'VETERANS LAW JUDGE', value: 'VETERANS LAW JUDGE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'SUPR VET LAW JUDGE', value: 'SUPR VET LAW JUDGE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'PROGRAM SPECIALIST', value: 'PROGRAM SPECIALIST', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'ADMIN SERVICE SPEC', value: 'ADMIN SERVICE SPEC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'ADMIN SERVICE MANAGE', value: 'ADMIN SERVICE MANAGE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAID_TITLE', content: 'CORRESPONDENCE SPEC', value: 'CORRESPONDENCE SPEC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 3/E', value: 'AL 3/E', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'ES', value: 'ES', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 2', value: 'AL 2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 3/D', value: 'AL 3/D', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'EX', value: 'EX', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'GENERAL', value: 'GENERAL', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'MEDICAL', value: 'MEDICAL', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 3/F', value: 'AL 3/F', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'SL', value: 'SL', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 3/C', value: 'AL 3/C', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 3/B', value: 'AL 3/B', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PAY_SCHED', content: 'AL 3/A', value: 'AL 3/A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PMS', content: '2', value: '2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PMS', content: '3', value: '3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PMS', content: '1', value: '1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PMS', content: '5', value: '5', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'PMS', content: '4', value: '4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '02REG', value: '02REG', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014DEV', value: '014DEV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '011', value: '011', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0111A1', value: '0111A1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '011A', value: '011A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '011B', value: '011B', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '011C', value: '011C', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '011D', value: '011D', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '011W', value: '011W', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '012', value: '012', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '012A', value: '012A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014', value: '014', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141A', value: '0141A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141B', value: '0141B', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141C', value: '0141C', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141D', value: '0141D', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141F3', value: '0141F3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141G', value: '0141G', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141L', value: '0141L', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01A', value: '01A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01B', value: '01B', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01C', value: '01C', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01C1', value: '01C1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01C2', value: '01C2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01C3', value: '01C3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01E', value: '01E', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014DS', value: '014DS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014DS1', value: '014DS1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014DS2', value: '014DS2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014DS3', value: '014DS3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014DS4', value: '014DS4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '0141DS', value: '0141DS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014HRG', value: '014HRG', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '014INT', value: '014INT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'ROUTE_SYM', content: '01', value: '01', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'SERVICE', content: 'A', value: 'A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'SERVICE', content: 'P', value: 'P', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '2', value: '2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '3', value: '3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '4', value: '4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '5', value: '5', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '6', value: '6', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '7', value: '7', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '8', value: '8', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '9', value: '9', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'A', value: 'A', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'B', value: 'B', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'C', value: 'C', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'D', value: 'D', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'E', value: 'E', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'F', value: 'F', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: 'N', value: 'N', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '10', value: '10', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '0', value: '0', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'STEP', content: '1', value: '1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK-GROUP', content: 'OVLJ', value: 'OVLJ', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_ GROUP', content: 'CLERICAL SPT BR', value: 'CLERICAL SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HUMAN RESOURCES', value: 'HUMAN RESOURCES', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'A1', value: 'A1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'A2', value: 'A2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'A3', value: 'A3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'A4', value: 'A4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'APP TM', value: 'APP TM', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CH', value: 'CH', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'D1', value: 'D1', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'D2', value: 'D2', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'D3', value: 'D3', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'D4', value: 'D4', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'MGMT', value: 'MGMT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'OPR', value: 'OPR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'VC/MIS', value: 'VC/MIS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'VC', value: 'VC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DEVELOPMENT', value: 'DEVELOPMENT', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DETAILED/LWOP', value: 'DETAILED/LWOP', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'D5', value: 'D5', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DISPATCH BR', value: 'DISPATCH BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE MGT BR', value: 'CASE MGT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE SPT BR', value: 'CASE SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'ADMN SPT DIV', value: 'ADMN SPT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DT SPT DIV', value: 'DT SPT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE MGT BR', value: 'CASE MGT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE MGT BR', value: 'CASE MGT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'FIN MGT DIV', value: 'FIN MGT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'FIN MGT DIV', value: 'FIN MGT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE SPT BR', value: 'CASE SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DISPATCH BR', value: 'DISPATCH BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DISPATCH BR', value: 'DISPATCH BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DISPATCH BR', value: 'DISPATCH BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CLERICAL SPT BR', value: 'CLERICAL SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'FIN MGT DIV', value: 'FIN MGT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE SPT BR', value: 'CASE SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CLERICAL SPT BR', value: 'CLERICAL SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'OMO BR', value: 'OMO BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'DIR OFC', value: 'DIR OFC', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CASE SPT BR', value: 'CASE SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'FIN MGT DIV', value: 'FIN MGT DIV', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'HEARING BR', value: 'HEARING BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'IT INVEN/SUPPLY', value: 'IT INVEN/SUPPLY', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'CLERICAL SPT BR', value: 'CLERICAL SPT BR', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_GROUP', content: 'WILKES BARRE', value: 'WILKES BARRE', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_LOCATION', content: 'ODS', value: 'ODS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_LOCATION', content: 'AWS', value: 'AWS', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'WORK_LOCATION', content: 'TW', value: 'TW', created_by: 'root@rms.config')

### ABOVE WAS IMPORTED FROM Vacols::Lists ###

Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'MILITARY_SERVICE_BRANCH', content: 'US Coast Guard', value: 'US Coast Guard', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'MILITARY_SERVICE_BRANCH', content: 'Army', value: 'Army', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'MILITARY_SERVICE_BRANCH', content: 'Navy', value: 'Navy', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'MILITARY_SERVICE_BRANCH', content: 'National Guard', value: 'National Guard', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'MILITARY_SERVICE_BRANCH', content: 'Marine Corp', value: 'Marine Corp', created_by: 'root@rms.config')
Bvadmin::RmsDropDownConfig.create(table_id: 'EMPLOYEE', field_id: 'MILITARY_SERVICE_BRANCH', content: 'Air Force', value: 'Air Force', created_by: 'root@rms.config')

