ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "POB_CITY" VARCHAR2(35);
ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "POB_STATE" VARCHAR2(2);
ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "POB_COUNTRY" VARCHAR2(40);
ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "MILITARY_SERVICE_BRANCH" VARCHAR2(20);
