ALTER TABLE "BVADMIN"."ATTORNEY" ADD "LICENSE" VARCHAR2(60);
ALTER TABLE "BVADMIN"."ATTORNEY" ADD "JURISDICTION" VARCHAR2(60);
ALTER TABLE "BVADMIN"."ATTORNEY" ADD "LAWSCHOOL" VARCHAR2(60);
ALTER TABLE "BVADMIN"."ATTORNEY" ADD "ATTORNEY_NOTES" VARCHAR2(600);
ALTER TABLE "BVADMIN"."ATTORNEY" ADD "PRESIDENTIAL_ADMIN" VARCHAR2(100);
