
CREATE TABLE "BVADMIN"."RMS_DROP_DOWN_CONFIG" (
  "ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "TABLE_ID" VARCHAR2(30) NOT NULL,
  "FIELD_ID" VARCHAR2(30) NOT NULL,
  "CONTENT" VARCHAR2(45) NOT NULL,
  "VALUE" VARCHAR2(45) NOT NULL,
  "CREATED_BY" VARCHAR2(60) NOT NULL
);

CREATE SEQUENCE "BVADMIN"."RMS_DROP_DOWN_CONFIG_seq" START WITH 10000;
