CREATE TABLE "BVADMIN"."EMPLOYEE_APPLICANTS" (
  "APPLICANT_ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "FNAME" VARCHAR2(17) NOT NULL,
  "LNAME" VARCHAR2(30) NOT NULL,
  "NAME" VARCHAR2(60),
  "DATE_OF_BIRTH" DATE,
  "SERIES" VARCHAR2(4),
  "GRADE" VARCHAR2(5),
  "PAY_PLAN" VARCHAR2(7),
  "EMPLOYEE_ID" NUMBER(38)
);
CREATE SEQUENCE "BVADMIN"."EMPLOYEE_APPLICANTS_seq" START WITH 10000;

CREATE TABLE "BVADMIN"."EMPLOYEE_APPLICATIONS" (
  "APPLICATION_ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "APPLICANT_ID" NUMBER(38) NOT NULL,
  "STATUS" VARCHAR2(30) NOT NULL,
  "ORG_CODE" VARCHAR2(25),
  "VACCANCY_NUMBER" VARCHAR2(12),
  "TITLE" VARCHAR2(30),
  "PROCESS_START_DATE" DATE,
  "SELECTED_DATE" DATE,
  "TENTATIVE_OFFER_DATE" DATE,
  "SENT_TO_SECURITY_DATE" DATE,
  "FINAL_OFFER_DATE" DATE,
  "REQUESTED_EOD" DATE,
  "CONFIRMED_EOD" DATE,
  "ORG_INFORMATION_ID" NUMBER(38),
  "COMMENTS" VARCHAR2(255),
  "EFFECTIVE_DATE" DATE
);
CREATE SEQUENCE "BVADMIN"."EMPLOYEE_APPLICATIONS_seq" START WITH 10000;

CREATE TABLE "BVADMIN"."RMS_USERS" (
  "USER_ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "EMAIL" VARCHAR2(60) NOT NULL,
  "NAME" VARCHAR2(120) NOT NULL
);
CREATE SEQUENCE "BVADMIN"."RMS_USERS_seq" START WITH 10000;

CREATE TABLE "BVADMIN"."RMS_ROLES" (
  "ROLE_ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(60) NOT NULL
);
CREATE SEQUENCE "BVADMIN"."RMS_ROLES_seq" START WITH 10000;

CREATE TABLE "BVADMIN"."RMS_ROLES_USERS" (
  "ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "USER_ID" NUMBER(38) NOT NULL,
  "ROLE_ID" NUMBER(38) NOT NULL
);
CREATE SEQUENCE "BVADMIN"."RMS_ROLES_USERS_seq" START WITH 10000;

CREATE TABLE "BVADMIN"."RMS_ROLE_PERMISSIONS" (
  "PERMISSION_ID" NUMBER(38) NOT NULL PRIMARY KEY,
  "ROLE_ID" NUMBER(38) NOT NULL,
  "TABLE_NAME" VARCHAR2(100),
  "FIELD_NAME" VARCHAR2(100),
  "READ_ACCESS" NUMBER(1) DEFAULT 1,
  "WRITE_ACCESS" NUMBER(1) DEFAULT 0
);
CREATE SEQUENCE "BVADMIN"."RMS_ROLE_PERMISSIONS_seq" START WITH 10000;
