CREATE VIEW "BVADMIN"."POTENTIAL_APPLICANTS" AS
  SELECT 'emp' AS "TABLE", EMPLOYEE_ID AS "ID", FNAME, LNAME, GRADE, JOB_CODE AS "SERIES" FROM "BVADMIN"."EMPLOYEE"
  UNION 
  SELECT 'app' AS "TABLE", APPLICANT_ID AS "ID", FNAME, LNAME, GRADE, SERIES FROM "BVADMIN"."EMPLOYEE_APPLICANTS";
