CREATE TABLE "BVADMIN"."TRAINING_NEW" (
    "ID" NUMBER(38) NOT NULL PRIMARY KEY,
    "USER_ID" VARCHAR2(6) NOT NULL,
    "CLASS_NAME" VARCHAR2(60),
    "CLASS_DATE" DATE
);

CREATE SEQUENCE "BVADMIN"."TRAINING_seq" START WITH 1;

INSERT INTO "BVADMIN"."TRAINING_NEW" ("ID", "USER_ID", "CLASS_NAME", "CLASS_DATE")
SELECT "BVADMIN"."TRAINING_seq"."NEXTVAL" AS "ID",
       "BVADMIN"."TRAINING"."USER_ID" AS "USER_ID",
       "BVADMIN"."TRAINING"."CLASS_NAME" AS "CLASS_NAME",
       "BVADMIN"."TRAINING"."CLASS_DATE" AS "CLASS_DATE"
       FROM "BVADMIN"."TRAINING";

-- Could probably DROP TABLE, but I don't feel comfortable being the one to do that.
ALTER TABLE "BVADMIN"."TRAINING" RENAME TO "BVADMIN"."TRAINING_ORIG";
ALTER TABLE "BVADMIN"."TRAINING_NEW" RENAME TO "BVADMIN"."TRAINING"
