ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "UNION" NUMBER(1) DEFAULT 0;
ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "UNION_TIMESPENT" VARCHAR2(12);
ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "UNION_START" DATE;
ALTER TABLE "BVADMIN"."EMPLOYEE" ADD "UNION_END" DATE;
